{{- $userUsername := "user" }}
{{- $userPassword := randAlpha 32 }}
{{- $adminUsername := "admin" }}
{{- $adminPassword := randAlpha 32 }}
{{- $sessionEncryptKey := randAlpha 32 }}
{{- $sessionValidateKey := randAlpha 32 }}
{{/*
  Fetch existing secrets
*/}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "pycloud-env") }}
{{- if $secret }}
{{- $userPassword = index $secret.data "users.user.password" | b64dec }}
{{- $adminPassword = index $secret.data "users.admin.password" | b64dec }}
{{- $sessionEncryptKey = index $secret.data "sessionEncryptKey" | b64dec }}
{{- $sessionValidateKey = index $secret.data "sessionValidateKey" | b64dec }}
{{- end -}}

{{- $values := dict "Values" .Values "adminUsername" $adminUsername "adminPassword" $adminPassword "userUsername" $userUsername "userPassword" $userPassword "sessionEncryptKey" $sessionEncryptKey "sessionValidateKey" $sessionValidateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "pycloud-env"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  users.user.password: {{ $userPassword | b64enc | quote }}
  users.admin.password: {{ $adminPassword | b64enc | quote }}
  sessionEncryptKey: {{ $sessionEncryptKey | b64enc | quote }}
  sessionValidateKey: {{ $sessionValidateKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "pycloud-config"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config.ini: {{ include "pypicloud.configini" $values | b64enc }}
